export const PAKISTANI_BANKS = [
  "Al-Baraka Bank (Pakistan) Limited",
  "Allied Bank Limited",
  "Askari Bank Limited",
  "Bank Alfalah Limited",
  "Bank Al-Habib Limited",
  "BankIslami Pakistan Limited",
  "Bank of Punjab",
  "Bank of Khyber",
  "Burj Bank Ltd.",
  "Citibank N.A.",
  "Deutsche Bank A.G.",
  "Dubai Islamic Bank Pakistan Limited",
  "Faysal Bank Limited",
  "First Women Bank Limited",
  "Habib Bank Limited",
  "Habib Metropolitan Bank Limited",
  "Industrial and Commercial Bank of China",
  "JS Bank Limited",
  "MCB Bank Limited",
  "MCB Islamic Bank Limited",
  "Meezan Bank Limited",
  "National Bank of Pakistan",
  "Samba Bank Limited",
  "Silkbank Limited",
  "Sindh Bank Ltd",
  "Soneri Bank Limited",
  "Standard Chartered Bank (Pakistan) Limited",
  "Summit Bank Limited",
  "Telenor Microfinance Bank",
  "UBL Ameen",
  "United Bank Limited",
  "Zarai Taraqiati Bank Limited"
];
